import {beforeAll,afterAll,describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import jwt from 'jsonwebtoken';
import buildServer from '../src/index';
import prismaModule from '../src/lib/prisma';
import sessionModule from '../src/lib/session';
const {createPrismaClient}=prismaModule,{hashToken}=sessionModule;
describe.skipIf(process.env.EXTERNAL_CATALOG_DATABASE_TEST!=='true')('external catalog with owned PostgreSQL fixtures',()=>{
 let app,db,cookie,listener,trackIds=[],recordIds=[],userIds=[];
 const suffix=randomUUID().slice(0,8),fixtureId='QA'+suffix;
 const m={externalId:fixtureId,title:'Owned Audius adapter fixture',artistName:'Owned fixture artist',durationSeconds:120,availability:'AVAILABLE',playbackMode:'EXTERNAL_STREAM',provenance:'AUDIUS_PUBLIC_API',checkedAt:new Date(),canonicalUrl:`https://audius.co/owned-fixture/fixture-${suffix}`,versionType:'UNKNOWN',provider:'AUDIUS'};
 const req=async(path,body,method='POST',auth=cookie)=>{const r=await app.inject({method,url:'/api/external-catalog'+path,headers:{cookie:auth,origin:'http://localhost:3000'},...(body?{payload:body}:{})});return {status:r.statusCode,body:r.json()};};
 const create=async(title='Owned recording fixture',versionType='UNKNOWN')=>{const r=await req('/recordings',{title,artistName:'Owned fixture artist',durationSeconds:120,versionType,provenance:'Owned synthetic test metadata',reason:'Owned fixture test'});expect(r.status).toBe(200);trackIds.push(r.body.recording.id);recordIds.push(r.body.recording.recordingId);return r.body.recording;};
 beforeAll(async()=>{
  if (process.env.NS_TEST_DISPOSABLE === 'true') { const purpose = new URL(process.env.DATABASE_URL).pathname.match(/_backend_([0-9]+)_test$/)?.[1]; if (!purpose) throw new Error('Owned backend test identity required'); (await import('../../scripts/integration/database-guard.cjs')).default.assertDatabaseScope(process.env, process.env.DATABASE_URL, `backend_${purpose}`); } else if (process.env.DATABASE_URL !== 'postgresql://catalog_test@127.0.0.1:55479/noirsound_external_test') throw new Error('Owned local test database required');
  process.env.JWT_SECRET='external-test-jwt-secret-32-characters';process.env.COOKIE_SECRET='external-test-cookie-secret-32-characters';process.env.EXTERNAL_CATALOG_ENABLED='true';process.env.RATE_LIMIT_MULTIPLIER='100';process.env.PUBLIC_APP_ENABLED='true';process.env.FRONTEND_ORIGIN='http://localhost:3000';
  db=createPrismaClient();
  async function session(role){const u=await db.user.create({data:{email:`external-${role.toLowerCase()}-${suffix}@example.test`,username:`qa_${role.toLowerCase()}_${suffix}`,displayName:'Owned QA fixture',role,status:'ACTIVE'}});userIds.push(u.id);const sid=randomUUID(),token=jwt.sign({userId:u.id,sid},process.env.JWT_SECRET,{expiresIn:'1h'});await db.session.create({data:{id:sid,userId:u.id,token:hashToken(token),expiresAt:new Date(Date.now()+3600000)}});return `token=${token}`;}
  cookie=await session('ADMIN');listener=await session('LISTENER');
  const audius={getTrack:async()=>m,resolve:async()=>m,search:async()=>[m],status:()=> 'LIVE',capabilities:{search:true},playback:async()=>({track:m,url:'https://creatornode.audius.co/tracks/cidstream/fixture',playbackMode:'EXTERNAL_STREAM',provider:'AUDIUS'})};
  app=buildServer({prisma:db,audius,storage:{},audioQueue:{close:async()=>{}},rateLimitRedis:null});await app.ready();
 });
 afterAll(async()=>{if(app)await app.close();if(db){await db.externalPlaybackEvent.deleteMany({where:{recordingId:{in:recordIds}}});await db.externalSource.deleteMany({where:{recordingId:{in:recordIds}}});await db.externalRecording.updateMany({where:{id:{in:recordIds}},data:{mergedIntoId:null,parentId:null}});await db.externalRecording.deleteMany({where:{id:{in:recordIds}}});await db.track.deleteMany({where:{id:{in:trackIds}}});await db.auditLog.deleteMany({where:{actorId:{in:userIds}}});await db.user.deleteMany({where:{id:{in:userIds}}});await db.externalCatalogSetting.deleteMany({where:{id:'beta'}});await db.$disconnect();}});
 it('rejects anonymous/listener API, direct URLs and cross-origin writes',async()=>{expect((await app.inject({url:'/api/external-catalog/search?q=fixture'})).statusCode).toBe(401);expect((await req('/search?q=fixture',null,'GET',listener)).status).toBe(403);expect((await app.inject({url:'/external-music'})).statusCode).toBe(302);expect((await app.inject({method:'POST',url:'/api/external-catalog/import',headers:{cookie,origin:'https://evil.example'},payload:{externalId:fixtureId}})).statusCode).toBe(403);});
 it('official embed API is private, gated, canonical and creates no catalog rows',async()=>{
  const path='/embed?'+new URLSearchParams({provider:'YOUTUBE',url:'https://youtu.be/abcdefghijk?si=tracking'});
  expect((await app.inject({url:'/api/external-catalog'+path})).statusCode).toBe(401);
  expect((await req(path,null,'GET',listener)).status).toBe(403);
  const count=await db.externalRecording.count();
  const result=await req(path,null,'GET');expect(result.status).toBe(200);expect(result.body.embedUrl).toBe('https://www.youtube-nocookie.com/embed/abcdefghijk?playsinline=1&autoplay=0');expect(await db.externalRecording.count()).toBe(count);
  const prior=process.env.EXTERNAL_CATALOG_ADMIN_IDS;process.env.EXTERNAL_CATALOG_ADMIN_IDS=randomUUID();
  try {expect((await req(path,null,'GET')).status).toBe(403);}finally{if(prior===undefined)delete process.env.EXTERNAL_CATALOG_ADMIN_IDS;else process.env.EXTERNAL_CATALOG_ADMIN_IDS=prior;}
  expect((await req('/embed?'+new URLSearchParams({provider:'SPOTIFY',url:'https://open.spotify.com/track/1234567890123456789012'}),null,'GET')).status).toBe(400);
 });
 it('repeated import is idempotent under real unique constraints',async()=>{const a=await req('/import',{externalId:fixtureId}),b=await req('/import',{url:m.canonicalUrl});expect(a.status).toBe(200);expect(b.body.recording.id).toBe(a.body.recording.id);trackIds.push(a.body.recording.id);recordIds.push(a.body.recording.recordingId);expect(a.body.recording.sources[0].officialStatus).toBe('UNVERIFIED');expect(a.body.recording.versionType).toBe('UNKNOWN');expect(a.body.recording.artistId).toBeNull();const bridge=await db.track.findUnique({where:{id:a.body.recording.id},include:{artist:{include:{user:true}},externalRecording:true}});expect(bridge.artist.userId).toBe(userIds[0]);expect(bridge.primaryArtistName).toBe(m.artistName);expect(bridge.artist.user.displayName).toBe('Owned QA fixture');expect(bridge.externalRecording.curatorId).toBe(userIds[0]);});
 it('LINK_OUT confirmation and primary selection require evidence',async()=>{const a=await create();const source=await req(`/recordings/${a.recordingId}/sources`,{provider:'YOUTUBE',url:'https://youtu.be/abcdefghijk',reason:'Fixture link supplied'});expect(source.status).toBe(200);expect(source.body.source.playbackMode).toBe('LINK_OUT');expect((await req(`/sources/${source.body.source.id}`,{matchStatus:'CONFIRMED',officialStatus:'VERIFIED',isPrimary:true,reason:'Fixture verification'},'PATCH')).status).toBe(400);expect((await req(`/sources/${source.body.source.id}`,{matchStatus:'CONFIRMED',officialStatus:'VERIFIED',isPrimary:true,evidence:'Synthetic fixture verification evidence',reason:'Fixture verification'},'PATCH')).status).toBe(200);});
 it('merge/unmerge keeps exact playlist, like and history rows and one card',async()=>{const a=await create(),b=await create();await req(`/recordings/${a.recordingId}/sources`,{provider:'YOUTUBE',url:'https://youtu.be/abcd1234567',reason:'Synthetic source A'});await req(`/recordings/${b.recordingId}/sources`,{provider:'SPOTIFY',url:'https://open.spotify.com/track/1234567890123456789012',reason:'Synthetic source B'});
  const userId=userIds[0],p=await db.playlist.create({data:{name:'Owned fixture playlist',creatorId:userId,isPublic:false}});await db.playlistTrack.create({data:{playlistId:p.id,trackId:a.id,order:1}});await db.trackLike.create({data:{userId,trackId:a.id}});await db.externalPlaybackEvent.create({data:{recordingId:a.recordingId,userId,provider:'AUDIUS',durationListenedSeconds:31}});
  const snapshot=async()=>JSON.stringify({likes:await db.trackLike.findMany({where:{trackId:a.id}}),playlist:await db.playlistTrack.findMany({where:{trackId:a.id}}),events:await db.externalPlaybackEvent.findMany({where:{recordingId:a.recordingId}})});const before=await snapshot();const sourceBefore=await db.externalSource.findMany({where:{recordingId:a.recordingId},select:{id:true,matchStatus:true,isPrimary:true,verificationEvidence:true}});
  expect((await req(`/recordings/${a.recordingId}/merge`,{intoId:b.recordingId,reason:'Synthetic same-recording review',evidence:'Owned synthetic identical metadata'})).status).toBe(200);
  const view=await req(`/recordings/${b.recordingId}`,null,'GET');expect(view.body.recording.primarySources).toHaveLength(2);expect(view.body.recording.members).toHaveLength(1);const list=await req('/recordings',null,'GET');expect(list.body.items.filter(r=>[a.id,b.id].includes(r.id))).toHaveLength(1);expect(await snapshot()).toBe(before);
  expect((await req(`/recordings/${a.recordingId}/unmerge`,{reason:'Reversibility fixture check'})).status).toBe(200);expect(await snapshot()).toBe(before);expect(await db.externalSource.findMany({where:{recordingId:a.recordingId},select:{id:true,matchStatus:true,isPrimary:true,verificationEvidence:true}})).toEqual(sourceBefore);expect(await db.auditLog.count({where:{targetId:b.recordingId,action:{in:['EXTERNAL_MERGE','EXTERNAL_UNMERGE']}}})).toBe(2);
 });
 it.each(['REMIX','LIVE','NIGHTCORE'])('cannot merge %s with an original',async version=>{const a=await create('Owned original fixture','ORIGINAL'),b=await create(`Owned fixture ${version}`,version);expect((await req(`/recordings/${b.recordingId}/merge`,{intoId:a.recordingId,reason:'Conflict fixture',evidence:'Fixture evidence'})).status).toBe(409);});
 it('beta records cannot leak to ordinary track/like/statistics APIs',async()=>{const r=await req('/import',{externalId:fixtureId});const id=r.body.recording.id;const pub=await app.inject({url:'/api/tracks'});expect(pub.statusCode).toBe(200);expect(JSON.stringify(pub.json())).not.toContain(id);expect((await app.inject({url:`/api/tracks/${id}`})).statusCode).toBe(404);expect((await app.inject({method:'POST',url:`/api/tracks/${id}/like`,headers:{cookie:listener,origin:'http://localhost:3000'}})).statusCode).toBe(404);expect((await app.inject({method:'POST',url:`/api/tracks/${id}/play-event`,headers:{cookie,origin:'http://localhost:3000'},payload:{durationListenedSeconds:31}})).statusCode).toBe(409);});
 it('saved links appear as ordinary private tracks without exposing them publicly',async()=>{
  const payload={title:'Owned SoundCloud normal-card fixture',artistName:'Owned fixture artist',provider:'SOUNDCLOUD',url:`https://soundcloud.com/owned-fixture/normal-card-${suffix}`,provenance:'Owned explicitly supplied fixture metadata',reason:'Ordinary card fixture'};
  const before=await db.externalRecording.count();const created=await req('/recordings',payload);expect(created.status).toBe(200);
  const track=created.body.recording;trackIds.push(track.id);recordIds.push(track.recordingId);
  expect(track).toMatchObject({provider:'SOUNDCLOUD',playbackMode:'OFFICIAL_EMBED',isStreamable:false,isAvailable:true,canSave:true,artistId:null});
  expect((await req('/recordings',payload)).body.recording.id).toBe(track.id);expect(await db.externalRecording.count()).toBe(before+1);
  const catalog=async(auth)=>{const r=await app.inject({url:'/api/discover/catalog?'+new URLSearchParams({q:payload.title}),headers:auth?{cookie:auth}:{}});expect(r.statusCode).toBe(200);return r.json();};
  expect((await catalog(cookie)).items).toHaveLength(1);expect((await catalog(cookie)).items[0]).toMatchObject({id:track.id,artistName:payload.artistName,artistId:null,artist:null,provider:'SOUNDCLOUD'});
  expect((await catalog(listener)).total).toBe(0);expect((await catalog()).total).toBe(0);
  const detail=await app.inject({url:`/api/tracks/${track.id}`,headers:{cookie}});expect(detail.statusCode).toBe(200);expect(detail.json().track.provider).toBe('SOUNDCLOUD');
  const playback=await req(`/recordings/${track.recordingId}/playback?sourceId=${track.selectedSourceId}`,null,'GET');expect(playback.status).toBe(200);expect(new URL(playback.body.embedUrl).origin).toBe('https://w.soundcloud.com');
  const events=await db.playEvent.count();const userId=userIds[0];const playlist=await db.playlist.create({data:{name:'Owned normal-card fixture',creatorId:userId,isPublic:false}});
  const add=await app.inject({method:'POST',url:`/api/playlists/${playlist.id}/tracks`,headers:{cookie,origin:'http://localhost:3000'},payload:{trackId:track.id}});expect(add.statusCode,add.body).toBe(200);
  const publicList=await db.playlist.create({data:{name:'Owned public fixture',creatorId:userId,isPublic:true}});
  expect((await app.inject({method:'POST',url:`/api/playlists/${publicList.id}/tracks`,headers:{cookie,origin:'http://localhost:3000'},payload:{trackId:track.id}})).statusCode).toBe(404);
  expect(await db.playEvent.count()).toBe(events);
  await req('/settings',{enabled:false,reason:'Ordinary catalogue gate fixture'},'PATCH');expect((await catalog(cookie)).total).toBe(0);await req('/settings',{enabled:true,reason:'Restore ordinary catalogue gate fixture'},'PATCH');
 });
 it('disables beta without deploy and preserves native API',async()=>{expect((await req('/settings',{enabled:false,reason:'Disable fixture beta'},'PATCH')).status).toBe(200);expect((await req('/search?q=fixture',null,'GET')).status).toBe(403);expect((await req('/embed?'+new URLSearchParams({provider:'YOUTUBE',url:'https://youtu.be/abcdefghijk'}),null,'GET')).status).toBe(403);expect((await app.inject({url:'/api/tracks'})).statusCode).toBe(200);expect((await req('/settings',{enabled:true,reason:'Reenable fixture beta'},'PATCH')).status).toBe(200);});
});
