export const DEFAULT_THEME = 'noir-pink';
export const SYSTEM_THEME = 'system';
export const THEME_STORAGE_KEY = 'noirsound.theme';

export const THEMES = Object.freeze({
  'noir-pink': Object.freeze({
    id: 'noir-pink',
    labelKey: 'themes.noirPink',
    descriptionKey: 'themes.noirPinkDesc',
    mode: 'dark',
    colors: Object.freeze({
      bg: '#0a0a0c',
      bgElevated: '#111115',
      card: '#111115',
      cardSoft: '#1b1b22',
      border: 'rgba(255, 255, 255, 0.06)',
      text: '#e4e4e7',
      textMuted: '#71717a',
      accent: '#f43f5e',
      accentSoft: 'rgba(244, 63, 94, 0.10)',
      accentStrong: '#e11d48',
      danger: '#f43f5e',
      success: '#10b981',
      warning: '#f59e0b',
    }),
  }),
  'midnight-blue': Object.freeze({
    id: 'midnight-blue',
    labelKey: 'themes.midnightBlue',
    descriptionKey: 'themes.midnightBlueDesc',
    mode: 'dark',
    colors: Object.freeze({
      bg: '#030712',
      bgElevated: '#081120',
      card: '#0f172a',
      cardSoft: '#162238',
      border: '#263754',
      text: '#f8fafc',
      textMuted: '#94a3b8',
      accent: '#38bdf8',
      accentSoft: 'rgba(56, 189, 248, 0.15)',
      accentStrong: '#0ea5e9',
      danger: '#fb7185',
      success: '#34d399',
      warning: '#fbbf24',
    }),
  }),
  'crimson-red': Object.freeze({
    id: 'crimson-red',
    labelKey: 'themes.crimsonRed',
    descriptionKey: 'themes.crimsonRedDesc',
    mode: 'dark',
    colors: Object.freeze({
      bg: '#070303',
      bgElevated: '#100808',
      card: '#171010',
      cardSoft: '#211414',
      border: '#3f1d1d',
      text: '#fff8f7',
      textMuted: '#b9a3a1',
      accent: '#ef4444',
      accentSoft: 'rgba(239, 68, 68, 0.16)',
      accentStrong: '#f97316',
      danger: '#fb7185',
      success: '#4ade80',
      warning: '#fbbf24',
    }),
  }),
  'royal-purple': Object.freeze({
    id: 'royal-purple',
    labelKey: 'themes.royalPurple',
    descriptionKey: 'themes.royalPurpleDesc',
    mode: 'dark',
    colors: Object.freeze({
      bg: '#07030f',
      bgElevated: '#10081a',
      card: '#171022',
      cardSoft: '#21152f',
      border: '#3b2750',
      text: '#fcf8ff',
      textMuted: '#b4a2c3',
      accent: '#a855f7',
      accentSoft: 'rgba(168, 85, 247, 0.16)',
      accentStrong: '#c084fc',
      danger: '#fb7185',
      success: '#4ade80',
      warning: '#fbbf24',
    }),
  }),
  'emerald-dark': Object.freeze({
    id: 'emerald-dark',
    labelKey: 'themes.emeraldDark',
    descriptionKey: 'themes.emeraldDarkDesc',
    mode: 'dark',
    colors: Object.freeze({
      bg: '#020806',
      bgElevated: '#07100d',
      card: '#0d1713',
      cardSoft: '#13231c',
      border: '#1e4639',
      text: '#f4fff9',
      textMuted: '#96b4a8',
      accent: '#10b981',
      accentSoft: 'rgba(16, 185, 129, 0.16)',
      accentStrong: '#34d399',
      danger: '#fb7185',
      success: '#4ade80',
      warning: '#fbbf24',
    }),
  }),
  'light-minimal': Object.freeze({
    id: 'light-minimal',
    labelKey: 'themes.lightMinimal',
    descriptionKey: 'themes.lightMinimalDesc',
    mode: 'light',
    colors: Object.freeze({
      bg: '#f7f7fb',
      bgElevated: '#ffffff',
      card: '#ffffff',
      cardSoft: '#f1f3f7',
      border: '#d8dce5',
      text: '#101014',
      textMuted: '#626672',
      accent: '#e11d48',
      accentSoft: 'rgba(225, 29, 72, 0.10)',
      accentStrong: '#be123c',
      danger: '#dc2626',
      success: '#059669',
      warning: '#d97706',
    }),
  }),
  'green-stream': Object.freeze({
    id: 'green-stream',
    labelKey: 'themes.greenStream',
    descriptionKey: 'themeDescriptions.greenStream',
    mode: 'dark',
    colors: Object.freeze({
      bg: '#050706',
      bgElevated: '#0b0f0d',
      card: '#111512',
      cardSoft: '#171d19',
      border: '#26332b',
      text: '#f7fff9',
      textMuted: '#a2afa7',
      accent: '#1ed760',
      accentSoft: 'rgba(30, 215, 96, 0.16)',
      accentStrong: '#22c55e',
      danger: '#ef4444',
      success: '#22c55e',
      warning: '#f59e0b',
    }),
  }),
  'orange-wave': Object.freeze({
    id: 'orange-wave',
    labelKey: 'themes.orangeWave',
    descriptionKey: 'themeDescriptions.orangeWave',
    mode: 'dark',
    colors: Object.freeze({
      bg: '#080604',
      bgElevated: '#110d09',
      card: '#17110d',
      cardSoft: '#211710',
      border: '#3b2a1d',
      text: '#fffaf5',
      textMuted: '#b9aaa0',
      accent: '#ff6a00',
      accentSoft: 'rgba(255, 106, 0, 0.16)',
      accentStrong: '#ff8a1d',
      danger: '#ef4444',
      success: '#22c55e',
      warning: '#f59e0b',
    }),
  }),
  system: Object.freeze({
    id: 'system',
    labelKey: 'themes.system',
    descriptionKey: 'themes.systemDesc',
    mode: 'system',
    colors: Object.freeze({
      bg: '#0a0a0c',
      bgElevated: '#111115',
      card: '#111115',
      cardSoft: '#1b1b22',
      border: 'rgba(255, 255, 255, 0.06)',
      text: '#e4e4e7',
      textMuted: '#71717a',
      accent: '#f43f5e',
      accentSoft: 'rgba(244, 63, 94, 0.10)',
      accentStrong: '#e11d48',
      danger: '#f43f5e',
      success: '#10b981',
      warning: '#f59e0b',
    }),
  }),
});

export const THEME_IDS = Object.freeze(Object.keys(THEMES));
export const CONCRETE_THEME_IDS = Object.freeze(
  THEME_IDS.filter((themeId) => themeId !== SYSTEM_THEME)
);

export function isThemeId(themeId) {
  return typeof themeId === 'string' && Object.hasOwn(THEMES, themeId);
}
